#ifndef COMPONENTS_INDEX_CPP
#define COMPONENTS_INDEX_CPP

#include "Tree.cpp"
#include "Background.cpp"
#include "BackgroundDemon.cpp"
#include "Bush.cpp"
#include "Cloud.cpp"
#include "DemonBoss.cpp"
#include "Explorer.cpp"
#include "ExplorerMirrored.cpp"
#include "Fireball.cpp"
#include "Firefly.cpp"
#include "FootGlow.cpp"
#include "Ghost.cpp"
#include "GiantSwordAttack.cpp"
#include "Goblin.cpp"
#include "GraveStone.cpp"
#include "GroundCracks.cpp"
#include "Heart.cpp"
#include "LoadingScreen.cpp"
#include "MenuBackground.cpp"
#include "PauseButton.cpp"
#include "PowerAttack.cpp"
#include "ReaperBoss.cpp"
#include "SummonSigil.cpp"
#include "TallGrass.cpp"
#include "Tree.cpp"

#endif